WITH T AS (
  SELECT
    P.KJNO
  , P.HOMON_ARG_NO
  , P.SD_COD
  , P.HOMON_ARG_BI
  , CASE 
      WHEN H.LO_COD IS NULL THEN NULL 
      ELSE LPAD(H.LO_COD, 4, '0') || LPAD(L.HIN_NUM, 2, '0') || LPAD(H.LO_CHARGE, 6, '0') 
    END AS L_COD
  , ROW_NUMBER() OVER (PARTITION BY P.KJNO, P.HOMON_ARG_NO, H.LO_COD ORDER BY H.LO_FR_BI DESC NULLS LAST) AS RN
  FROM HMN_PCDAT P
  LEFT JOIN HMN_LODAT L ON L.KJNO = P.KJNO AND L.HOMON_NUM = P.HOMON_ARG_NO
  LEFT JOIN HMN_LOHIS H ON H.LO_COD = L.LO_COD AND H.LO_FR_BI <= P.HOMON_ARG_BI
  WHERE P.STATUS = 5
), T2 AS (
  SELECT 
    KJNO
  , HOMON_ARG_NO
  , SD_COD
  , HOMON_ARG_BI
  , CASE 
      WHEN LISTAGG(L_COD, '-') WITHIN GROUP (ORDER BY L_COD) IS NULL THEN NULL
      ELSE '-' || LISTAGG(L_COD, '-') WITHIN GROUP (ORDER BY L_COD) 
    END AS LO_HINCD
  FROM T 
  WHERE RN = 1
  GROUP BY KJNO, HOMON_ARG_NO, SD_COD, HOMON_ARG_BI
), T3 AS (
  SELECT
    T2.KJNO
  , T2.HOMON_ARG_NO
  , T2.LO_HINCD
  , LPAD(S.SD_COD, 6, '0') || LPAD(S.SD_CHARGE, 6, '0') AS SD_HINCD
  , ROW_NUMBER() OVER (PARTITION BY T2.KJNO, T2.HOMON_ARG_NO, S.SD_COD ORDER BY S.SD_FR_BI DESC NULLS LAST) AS RN
  FROM T2
  INNER JOIN HMN_SDHIS S ON S.SD_COD = T2.SD_COD AND S.SD_FR_BI <= T2.HOMON_ARG_BI
)
SELECT 
  P.KJNO
, P.HOMON_ARG_NO
, T3.SD_HINCD || T3.LO_HINCD AS HIN_COD
FROM HMN_PCDAT P
INNER JOIN T3 ON T3.KJNO = P.KJNO AND T3.HOMON_ARG_NO = P.HOMON_ARG_NO AND T3.RN = 1;
